triggers:
   - name: trigger-dv-man
     type: trigger
     version:
       counter: 780
   - name: triggertest2
     type: trigger
     version:
      #message: 'new teswt2'
       counter: 2
      
  #- name: triggertest3
   # type: trigger
  #  source:
   #   message: 'tewwt3'
    #  counter: 3
